spring:
#  profiles:
#    active: dev1
  freemarker:
    check-template-location: false
  error:
    include-exception: true
    include-stacktrace: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true # sql prettier
#    show-sql: true
    open-in-view: false # 안쓰면 warning 뜸