spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1065811857075-bupikkeo2nj5nltogelil8qa7hvmrrgr.apps.googleusercontent.com
            client-secret: sSSLJs8IGl0I6ri5mX8Ty5vQ
            # 여기서 profile, email을 scope로 강제로 등록한 이유는 openid라는 scope가 있으면 Open Id Provider로 인식하기 때문이다.
            # 이렇게 되면 OpenId Provider인 서비스(구글)와 그렇지 않은 서비스(카카오 등)로 나눠서 각각 OAuth2Service를 만들어야 한다.
            scope: profile, email