spring:
  freemarker:
    check-template-location: false
  error:
    include-exception: true
    include-stacktrace: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true # sql prettier
#    show-sql: true
    open-in-view: false # 안쓰면 warning 뜸
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

cloud:
  aws:
    s3:
      bucket: s3doraboda
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
