spring:
  # postgresql
  datasource:
    platform: postgres
    url: jdbc:postgresql://yapp-18th-retrospect.cfyxps9nhs1l.ap-northeast-2.rds.amazonaws.com:5432
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
